import Link from 'next/link'
import './globals.css'
import { Inter, Azeret_Mono } from 'next/font/google'

const main = Azeret_Mono({ subsets: ['latin'] })
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blinkr app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={main.className}>
        <div className="flex flex-col gap-6 md:gap-8 lg:gap-10 xl:gap-12 p-6 md:p-8 lg:p-12 xl:p-24">
          <header>
            <Link href={'/'}>
              <h1 className={`text-4xl ${main.className}`}>Blinkr.</h1>
            </Link>
          </header>
          {children}
        </div>
      </body>
    </html>
  )
}
